flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.19.0
=======
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.0.5
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
